# docker compose for orchestrating local development containers
web:
    build: ./dev
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
        - .:/app
    ports:
        - "8000:8000"
